name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        mkdir build
        cd build
        cmake C:/Users/zatib/source/repos/software_for_hotel
    - name: build
      run: |
        cmake --build build --config Release
    - name: run-tests
      run: |
        cd build
        ctest -C Release --output-on-failure
